### PR TITLE
Remove wfRestoreWarnings and wfSuppressWarnings

### PR DESCRIPTION
**Pull request by paladox**
This is not needed.

### CODE REVIEW

**Comment by Hutchy68** [comment]
Don't think we can if we are going to support older versions of MW with foreground.

http://comments.gmane.org/gmane.science.linguistics.wikipedia.technical/83050

**Comment by paladox** [comment]
Hi this isen't needed unless there is code in here that needs it.

**Comment by Hutchy68** [comment]
But we suppressing them at the top.  We shouldn't surpress and then not restore them.  Remove the suppress first and then test.  The call to suppress the warnings is from the very early in Development.  Not sure if it is actually needed but I believe that is in the skinning manual which was followed when Foreground was first created.

**Comment by paladox** [comment]
@Hutchy68 oh ok. Well I doint think that was needed in a skin for a long time for example vector looking at mw 1.19 it doesn't use this. So I would assume it works without it.

**Comment by Hutchy68** [comment]
With this PR applied. So I guess the point is to not break the skin with warnings unless you are the developer checking for them.

suppresswarnings

**Comment by paladox** [comment]
Well looks like we found a error. It would help.

Do you know what the full error message says.

**Comment by paladox** [comment]
This hook is deprecated wfRunHooks in mw. I will upload a patch that fixes this.

**Comment by Hutchy68** [comment]
Yes, we found an error. The question is do we want users who are updating MW to see these errors and break the skin. Adding to 1.2.1 milestone so we can ask more about the original purpose of suppressing the warnings. I post something on MW list.

**Comment by paladox** [comment]
If we were too remove this users would be able to tell us that there are errors so we can go and fix it.

**Comment by Hutchy68** [comment]
Hey, I totally agree it would be great to get feedback if something breaks.  But what we need to know is does it suppress errors just for the skin or all extensions that are rendering content within the skin too. Vector  is closely watched as well as the extensions that are enabled on Wikimedia foundation's websites.

Not being difficult I just want to know what it does and why. It's always been part of the skinning manual  so perhaps their docs just need to be updated.

**Comment by paladox** [comment]
Ok.

**Pull request closed without merging**
